const { Resend } = require("resend");

const resend = new Resend(process.env.RESEND_API_KEY);

function generateTable(title, bookings) {

  if (!bookings || bookings.length === 0) {
    return `
      <div class="card">
        <h2>${title}</h2>
        <p class="empty">No bookings</p>
      </div>
    `;
  }

  const rows = bookings.map(b => `
    <tr>
      <td>${b.name || "-"}</td>
      <td>${b.phone || "-"}</td>
      <td>${Array.isArray(b.tables) ? b.tables.join(", ") : b.tables || "-"}</td>
      <td>${b.amount || "-"}</td>
      <td>${new Date(b.bookingDateTime).toLocaleString("th-TH")}</td>
      <td>${b.status || "-"}</td>
    </tr>
  `).join("");

  return `
    <div class="card">
      <h2>${title} (${bookings.length})</h2>
      <table>
        <thead>
          <tr>
            <th>ชื่อลูกค้า</th>
            <th>เบอร์</th>
            <th>โต๊ะ</th>
            <th>จำนวน</th>
            <th>เวลา</th>
            <th>สถานะ</th>
          </tr>
        </thead>
        <tbody>
          ${rows}
        </tbody>
      </table>
    </div>
  `;
}

async function sendEmailWithAttachment(date, attachments, data) {
  try {

    const formattedAttachments = attachments.map(a => ({
      filename: a.filename,
      content: a.content.toString("base64")
    }));

    const html = `
      <html>
      <head>
        <style>
          body {
            font-family: Arial, sans-serif;
            background: #f4f6f8;
            padding: 20px;
          }

          .container {
            max-width: 900px;
            margin: auto;
          }

          .header {
            text-align: center;
            padding: 20px;
            background: #111827;
            color: white;
            border-radius: 10px;
            margin-bottom: 20px;
          }

          .card {
            background: white;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.05);
          }

          h2 {
            margin-bottom: 10px;
            color: #111827;
          }

          table {
            width: 100%;
            border-collapse: collapse;
          }

          th {
            background: #f3f4f6;
            text-align: left;
            padding: 8px;
            font-size: 14px;
          }

          td {
            padding: 8px;
            border-top: 1px solid #eee;
            font-size: 13px;
          }

          tr:hover {
            background: #fafafa;
          }

          .empty {
            color: #999;
            font-style: italic;
          }

          .footer {
            text-align: center;
            font-size: 12px;
            color: #888;
            margin-top: 20px;
          }
        </style>
      </head>

      <body>
        <div class="container">

          <div class="header">
            <h1>📊 Daily Reservation Report</h1>
            <p>${date}</p>
          </div>

          ${generateTable("🎧 Stereo", data.stereoBookings)}
          ${generateTable("🍹 Coolly", data.coollyBookings)}
          ${generateTable("🌅 ViewBar", data.viewbarBookings)}
          ${generateTable("🏡 The View Village", data.theviewBookings)}

          <div class="footer">
            Auto-generated by Reservation System
          </div>

        </div>
      </body>
      </html>
    `;

    const response = await resend.emails.send({
      from: "Reservation System <onboarding@resend.dev>",
      to: ["theview.reservation@gmail.com"],
      subject: `Daily Reservation Report - ${date}`,
      text: `Reservation report for ${date}`,
      html: html,
      attachments: formattedAttachments
    });

    console.log("✅ Email sent:", response);

  } catch (error) {
    console.error("❌ Email sending failed:", error);
  }
}

module.exports = sendEmailWithAttachment;